root = "."
testdata_dir = "./testdata"
tmp_dir = "./tmp"

[build]
  full_bin = "./build/fullstack-go"
  cmd = "go build -o ./build/fullstack-go main.go"
  args_bin = []
  exclude_dir = ["static", "web"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  include_ext = ["go"]
  kill_delay = "0s"
  delay = 500
  log = "./tmp/build-errors.log"
  send_interrupt = false
  stop_on_error = true

[color]
  app = "blue"
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = false

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = false
